#!/bin/sh

VERSION=2.3.1
BASEDIR=$PWD
ROOTFS=$BASEDIR/ROOTFS
SRCDIR=$BASEDIR/OpenFOAM-$VERSION

# Check whether we need to download the tarbalj0j0
if [ ! -f OpenFOAM-$VERSION.tgz ]; then
    wget http://downloads.sourceforge.net/foam/OpenFOAM-$VERSION.tgz
fi
# Extract the target version
tar zxf OpenFOAM-$VERSION.tgz

## Patch bashrc to request debug compilation.
#cd $SRCDIR
#patch -p1 < $BASEDIR/patches/debug.patch

# Set OpenFOAM's environment variables required to build the package. You should change this to cshrc if
# that's the shell you are using.
export FOAM_INST_DIR=$BASEDIR
. $SRCDIR/etc/bashrc

# First, compile the wmake used to build OpenFOAM sources.
cd $SRCDIR/wmake/src
make

# Patch the solidMixtureProperties library
cd $SRCDIR
patch -p1 < $BASEDIR/patches/solidMixtureProperties-dependency.patch

# Make the OpenFOAM library
cd $SRCDIR/src
./Allwmake

# Apply the patch changing WMake options to position independent executables.
cd $SRCDIR
patch -p1 < $BASEDIR/patches/pie.patch

# Go and build the simpleFoam
cd $SRCDIR/applications/solvers/incompressible/simpleFoam
wmake

cd $BASEDIR
mkdir -p $ROOTFS/usr/lib
mkdir -p $ROOTFS/usr/bin
mkdir -p $ROOTFS/openfoam

cp $SRCDIR/platforms/$WM_OPTIONS/bin/simpleFoam  $ROOTFS/usr/bin

ldd $SRCDIR/platforms/$WM_OPTIONS/bin/simpleFoam | grep -Po '(?<=> )/[^ ]+' | sort | uniq | grep -Pv 'lib(c|gcc|dl|m|util|rt|pthread|stdc\+\+).so' | xargs -I {} install  {} $ROOTFS/usr/lib
# Also install libfieldFunctionObjects.so as it is not linked from the simpleFoam
install $SRCDIR/platforms/$WM_OPTIONS/lib/libfieldFunctionObjects.so $ROOTFS/usr/lib
install $SRCDIR/platforms/$WM_OPTIONS/lib/libforces.so $ROOTFS/usr/lib

# Copy the configuration files and scripts to the image.
cp -r $SRCDIR/etc $ROOTFS/openfoam
# Copy the case to be executed within the OSv instance (currently, this is hardcoded).
cp -r $BASEDIR/airFoil2D_05 "$ROOTFS/openfoam/case"

echo "
/usr/bin/simpleFoam:${ROOTFS}/usr/bin/simpleFoam
/usr/lib/**:${ROOTFS}/usr/lib/**
/openfoam/etc/**:$ROOTFS/openfoam/etc/**
/openfoam/case/**:$ROOTFS/openfoam/case/**
" > usr.manifest
