#!/bin/sh

# exit on error
set -e

## VERSION=v1.10.2  # 799148f8
# VERSION=v1.10.1  # b80f8028
VERSION='features/ompi-osv-v1b'  # cc94b1df
BASEDIR="$PWD"
SRCDIR="$BASEDIR/ompi-release"

CONFIGURE_FLAGS=""
if [ "$mode" = "debug" ]; then
    CONFIGURE_FLAGS="--enable-debug"
else  # release
    CONFIGURE_FLAGS="--with-platform=optimized"
fi
echo "Using OpenMPI CONFIGURE_FLAGS=$CONFIGURE_FLAGS"

# enable parallel build
export MAKEFLAGS="-j `nproc`"

if [ ! -d ompi-release ]; then
    # Checkout code
    git clone --depth 1 --branch $VERSION https://github.com/justinc1/ompi-release.git 
fi


mkdir -p $HOME/openmpi-bin
if [ ! -f ompi-release/build-osv/AAA-build-ok ]
then
    # Configure and compile
    export AUTOMAKE_JOBS=`nproc`
    (cd ompi-release && ./autogen.pl)
    #
    mkdir -p ompi-release/build-osv
    cd ompi-release/build-osv
    #
    ../configure --prefix=$HOME/openmpi-bin --disable-dlopen \
        --disable-oshmem --disable-posix-shmem --disable-sysv-shmem \
        CFLAGS="-fPIC -DPIC" --disable-pty-support --disable-vt \
        --enable-static --enable-shared $CONFIGURE_FLAGS
    make -j `nproc`
    chmod a+x ../make-orted-so.sh  # TODO fix git
    ../make-orted-so.sh

    # No need to install OpenMPI to get it compiled for OSv.
    # But mpicc is needed to compile OpenFOAM, so we install it anyway.
    #
    # To compile OpenFOAM, it would be enough to install system supplied 
    # OpenMPI, but then a simple 'mpirun ...' would use wrong binary.
    # This would require additional messing with PATH/LD_LIBRARY_PATH.
    make install  # safe with -prefix=$HOME/openmpi-bin
    # add to $PATH, $LD_LIBRARY_PATH ...
    if [ -z "`cat ~/.bashrc | grep 'MAGIC LINE mike-apps OpenMPI included'`" ]; then
        cat <<EOF >> ~/.bashrc

# MAGIC LINE mike-apps OpenMPI included : OSv mike-apps openmpi bin/libs 
export PATH=$HOME/openmpi-bin/bin:\$PATH
export LD_LIBRARY_PATH=$HOME/openmpi-bin/lib:\$LD_LIBRARY_PATH

EOF
    fi
    date >> AAA-build-ok
fi


echo "
/usr/lib/libibverbs.so.1:   /usr/lib/libibverbs.so.1
/usr/lib/libmpi.so.12:      ${SRCDIR}/build-osv/ompi/.libs/libmpi.so.12
/usr/lib/libmpi.so.1:       ${SRCDIR}/build-osv/ompi/.libs/libmpi.so.12
/usr/lib/libopen-pal.so.13: ${SRCDIR}/build-osv/opal/.libs/libopen-pal.so.13
/usr/lib/libopen-rte.so.12: ${SRCDIR}/build-osv/orte/.libs/libopen-rte.so.12
/usr/lib/orted.so:          ${SRCDIR}/build-osv/orte/tools/orted/.libs/orted.so

/usr/local/share/openmpi/help-opal-shmem-mmap.txt: ${SRCDIR}/opal/mca/shmem/mmap/help-opal-shmem-mmap.txt
" > "$BASEDIR/usr.manifest"
